using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using vJassMainJBlueprint.Utils;
using vJassMainJBlueprint.V1.ProjectEditor.Overlays;

namespace vJassMainJBlueprint.V1.ProjectEditor.Tools
{
    /// <summary>
    /// ProjectEditElementSampleIcons.xaml에 대한 상호 작용 논리.
    /// 샘플 이미지를 로드하고, 사용자가 클릭하여 이미지를 클립보드에 복사할 수 있도록 처리합니다.
    /// </summary>
    public partial class ToolSampleIcons : UserControl
    {
        /// <summary>
        /// 어플리케이션에서 제공하는 샘플 이미지들의 Base64 문자열 배열입니다.
        /// </summary>
        private static readonly string[] SampleImagesBase64 = [
            // 에디터 아이콘 - 트리거
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABOSURBVDhPYwCC/xRirIKkYAhDS0sLTmPDyGrQMKoB2ACyHBZDSDMABNAMId4AHBjCIGQAOobpA2LCBqCDUQMGvQFkYAgDZAApGKKP4T8AQesYO/c82a0AAAAASUVORK5CYII=",
            // 에디터 아이콘 - 이벤트
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB1SURBVDhP7Y5BDoAgDAS9cObTXHwVV3+FLJs1TSUKeNVk0ol2t271KR+h5Jz9h1EoKaU2SwgNvR+A4gsmiii9giPGa2oP7MYrFF9gw5gIwV0Y3AsmwoCiAiwpZMPa60BRgS49XPRQ7B+8XPRQVLAA5S9YZSsnW7Q5v97aunkAAAAASUVORK5CYII=",
            // 에디터 아이콘 - 조건
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACESURBVDhPpY5BDoAgDAQNdz/Czzn7IX+C3WBJabYEdMkELO3gIak/ocUd2qGU0neG7XGMAhZ7RyR7AsRJ1gUB7cAE+o07j84Jc4GvIVQQccrCbkMFaJwt9Gj4H9xzrIQK0pUoXSI9GAwFIW4YoQItYldyzr1mo70vo+AD7aCvrtLmjvoANHj1/RTvZLwAAAAASUVORK5CYII=",
            // 에디터 아이콘 - 액션
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB4SURBVDhPnY6LEcAgCEPdzVXcfwVrqvFT0xPk7l2FJoFQKv+RUuqo/w05fE0sd8C8+WAG6wAGlsEMRjNvNZpBfcDAcphBfVxsJqP5mudQRdMNwwwFp29hacwsASTGaAJaeYESK7YAosQKaOUFHrYLMPBAXw+4I+QHheNn1CaduqAAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 조건식(물음표)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEUSURBVDhPtZK9SgNREIVnCt27ie9nK9iYwiKVIQkiigjBQCCGRAt/iJ0PIDYBEVGwsbTRRgvxJY5n7ubibnbdqGDxwTIz57tzLysPY0Hg/lRw2RcMGoKNFcH6coJ9W816NpPOeIFIFlXF0rui+kZeyJP62uxcocCHPxTxERmSvsL1FJXHvCQnCCf78Ohr2HUp6VByl5XkBNXX6akk1AJuj5Id9iZlgmcOHCSEWsDtKqIt0i4RfIetHW2TTdL8pcDClZtpuJXdbK7AwvF1cdgoFfgwH8zunF47TakgvkqCUaM4bMzdwCjqBf5X4M7544zJ2R+v4I4VizXFwtoPBGkmh4JRU9BeFbTIfl1w0RHcnmTnEgSfVCRvhijScoQAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 변수(X=)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACySURBVDhPYzi9mOE/JRhsAAMDeRisd2UHpgSxGGxAoh+mBLEYbAD3VYb/MIxNET757ZOBtI8tw3/O6YxgjK4IJg7CyOIw3JoNpKuTIBx0Q9A1I7sEhsHeX90J0YBuCLJmdANhGGzAwdkIA9AVIotjwxkhQBqbC2AY5BKYHLLTYRjsAvQwAGFkPkghNsNBGGwAciyAMMxGbIagY3As4NIMw/gMAacDilMixXkBRJCPGf4DAPSHeK6X1q1WAAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 변수(X=, 붉은색)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACySURBVDhPYzi9mOE/JRhsAAMDeRisd2UHpgSxGGxAoh+mBLEYbMBVBrH/MIxNET757ZOBtI8tw//pjAJgjK4IJg7CyOIw3JoNpKuTIBx0Q9A1I7sEhsHeX92JMBHZEGTN6AbCMNiAg7MRBqArRBbHhjNCgDQ2F8AwyCUwOWSnwzDYBehhAMLIfJBCbIaDMNgA5FgAYZiN2AxBx+BYwKUZhvEZAk4HFKdEivMCiCAfM/wHAH9ieu2UqO4CAAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 변수(X=, 암녹색)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACxSURBVDhPYzi9mOE/JRhsAAMDeRisd2UHpgSxGGxAoh+mBLEY4vr/r/7DMZoCMMYjv30ykPaxBRJ7l0MwuiKYOAgji0NxazaQrk6CCqAbgq4Z2SVQDPb+6k6oAeiGIGtGNxCKwQYcnA1VgE0hsjgWnBECpLG6AIZBLoHJITkdhsEuwAgDEEbmgxRjMxyIwQagxAIIw2zEZggaBscCTs0wjMcQcDqgOCVSnBdABPmY4T8A+RCzh4mzrSwAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 트리거(톱니바퀴)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADHSURBVDhPjZExDsMwDAP1z26ZPXX07j90z+qf5AV+TQoKYUpbAtLhAIciGUexY7cz41NnMg/wArOcMYaTzUAoWM2tNUc19UwFvfc7gDOMpRQH53UeCgDMGDK4whn9oaDWOgWoqwYP9VCgb6dGqPP6wLP4RRD1mzWocM6dIGvv12/b/xbQj6wXrIasJJt51q9xCXoLNaoGD3XPcon4JhZs2+YwpM/wcJHhL2g7nzON51CwwhtkM/BY8MRdkIEFYcsA58xz7HZ+ARr817xludcmAAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 게임(고블린)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAI0SURBVDhPnVNNaxNRFH0zmaRpEmfGSTKZMUmTyZjUNLGZJJapFiXxo4kuQqnGRaGLgvgBBlFREQpuBUWEQruUKi7cCFm5VuhK8BcJx7lvGDWt2bg43Hfve+e8+/Ee+/6B4TAO3jF82WH49NIHrSn2r7NcgLH/w4SA67ro9/vchiMMQojBzKWgmxr3SyUTjuOg2+3Ctu0/ApQaObqhcxtTojimh5DQZtBsN1Crn+bxeFLilpDJ5rjlXKqPB6sMalKGUZ/F2uMM0laYx1VDQmUphs6mCnPORO5kCmeHMt/j3M+vfIFzQwX5FsPyuoKVDRk3n2egmRI2tk307ipwb8jQqyJ6dxRYjsI5nBtkoOYlaEWG+29rWHuUQ+WSgO2P87i4paByRcRoZwGqxVBsSZiz/RI4N+gBIZH2GlcTsfe1hwe7VVzYlHD9WRL7P66i3NC8CwTotoR8ocDPc24whUWn4TWPYfgiivQJrxfFGG6/LsBajPBJULy+KiEmi6gu+I2dGCONSBRFnOoI6I9CkOIMT9/7BwdPwsg2GKRZAWfaS5NjDAQIK+sJyIUQxuN9GKUZaCUGoypwP9gnO1Xg8lYCmkcol0sY7ebw7eeQ22bTz4T2yVK2RwToFcrH41AsAav3oph3E2hdU2G3Fe7rXgl0zl12MRgMjgpQWiRC63SZeROIYO+gg94tBapXCsXpZiJPLeFvWH2G7sMIsucZUob/Kg/jt0AAmis9juAbj9/4mP6tGX4BeAyZLYyjKwoAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 영웅(왕관)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACcSURBVDhPYzi9mOE/JRhsAAMDeXgkGPDwBjMYY5MDYRQDbp5CVXjjPNP/basgGMRGloMZimLAqU0scIXn9jP9X9ALVCTQ/p9B+imYDRIDyYHUgNRiNWDHIha4ZpDNIHGQISA2zBCQGqwGgBSCJEE03ACQC4ByMAOQ1WAYcOUoMxif2MUExpdPo2KYOEjNvXPYXEAGHk4GkI8Z/gMAy/ebq90Hh+MAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 선택(사람과 초록색 오오라)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADBSURBVDhP3ZMxDsIwDEV9Q67AObqyICF14QAIMbEgMXECpkpMTByAawT/H8cNkVuJjqh6smt//6ZtIsNJUsv9IOm2l3TeZpCjFmlpILKMb4O38rL4ULrqKZqzVmuKAZZGg6PFCjdo6kXLWbwfi+sJcQM1qkXO2ctubPwCZjjrK8B7IhrRgGNazvo3eFo0Zg1My1lv4qpEswamZd2bgUGUk382wDbd5Abrq4zfa4+a0GABblDAf8XmKMf42memj7WkD3u/qQTFclkYAAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 유닛(사람)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACNSURBVDhP3ZMxCoAwDEVzfEFw8QAOTi6Ckydw8lCRn5IaSlKro8ODkp//G21L50xcckzE+0i8dAmsUfN6JYDoG48BeRdHA6JhNE8ETwHixfdpodas2B7xrv0tvAEe8doJLJ6hRLzRP2gJEG8ktgRIvSo6a8ufA1ArA6K+cIIWcoCCc8Xl0Ge8DYn4WRNfH5+NPj2Fa/0AAAAASUVORK5CYII=",
            // 트리거 아이콘 - 유닛 그룹(사람들)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADWSURBVDhPYzi9mOH/9skM/1uzGf4n+kEwiA0SA8kRwgwghQwMEAwXhPIJYbDa6mRUAZINcDHHlEDG+AwEy8FsJYRBGuoTGP5PKUAYAPZ+gAOEg00DOm5NRTUA7P3OPAgHmwEpPgjF2DDY+8taIRx0AxwNGf5XRkNsxIdRDICZjMyGYQyNQDGw9ykxAOz9WTUQDjkGgC2HJSRiDEBngw3ICIFoQDcA3RCcBoAyDkwCH8ZmANj7yJkJH8ZmANj7MOdiw+u6Gf6DvAjSAML2RhAM42eEMPwHAOTvmUpzEyd2AAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 장식물(나무)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFWSURBVDhPYzi9mOE/Mt4+meF/QzrDfx9bhv98/xn+s2ZA2CAxkBy6erABDAyYGKSZayfEALYi7GrwGsB9mOE/ezUQlwMNyMWuBqcBINvRxdi7McXwugDkbNYIhv/Mhgz/WUKxq8FpAOcioI1lQANiGf4zqQMNcMIeDjgN4D4NNGQukN4O1OwOcQnRXuB9BAl57gNATSVAdjTQkECG/xyTIC5DVovVAFDUIfORMborsBoAwmBbPYEBaAINRHxhcHQ+qiDPDYj/OadBwoA1CIgTIYHKXomqFqwXlDxhArwvIV5gywEadBGqqRgSBqypQAwMG/Z6hHqw3nVQf4E0wyRAWEmU4b8AJ8N/UR6G/7JCqHJc6yE0WC+yC5Bxog3DfxtVCM5zxq4GrBc9DGAYpCnEGIJxGQDWCwpJZLy6k+F/GjDgmgMY/kdbQHA3MCmDxEByqOoZ/gMAu5ZxQZCoHNkAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 환경(번개구름)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKsSURBVDhPdVPfT5JhGAUENIRibKkLGIUROitLJH6ooH6mI9S+hjKUsULJDNGcYzoFYYCgIKWVUs2WM1fOtWaui9aFtZVbZhetrcv+l9P3fW3ANC/OxbP3nPM+z/Oel/VjnYWD+P6Sg93VQuysnMD75VPYXFDh7aPT+ETV9Fk+lzFgsXLgcDiQSCTQaDTo6uqC3+9HOBxGKBSCw+GAVCpFQUEBw80asNls8Hg8CAQCRtzQ0AC3241IJIJEIpE1mZ6eBkEQEAqFOYP9dTYjVCqV0Ol0sFqt8Hg88Hq9h+ByuaDX66FQKMDn80FrWd/WeIzYZrMhFoshGo0inU4zgkAggGQyidHRUaYeHx9nuqK5arUaX1eLwPryQsDcTJMymQxSqRSCwSBTB0JzmJiYxODdexgc8iMyM8+cx+Nx2O12asHSnIHP58Ps7Cwjdnu8IEkSrsEEnN6HsHaPwT6wALc3zHRC72NqagobD9S5Ea529IFo70Ndaz/qCSeaiVY0tdkxPPkEbl8ahMUBk6kRZrMZBlMnxSHxZrE8t0R1VS10RD9qW4ZQU2eDqZlE241hvPv4G6HkJowmC9p7A7D0RFF/bQRaQyuVE/HhZxSJRJArVNA39uDWSAY7u39AWD1Qqi5Da7RAo2+B6lwlxGIx9taoPBwMEpsKUpmsAvbb85TBEta3fuK8lkR5VRNKZZU4JjgOLnUZHbhskPINaHQ6gyA6h6kRxrCysY/eOykoK80ok18Av0hIdcxheEcalMnUkJScgbHlJl5t/4LdPcO8RkV1M0TikizvSAMutxCyci2cAzNIP/uMakM3Lhmuo8ZIjVKhy/L+a0C3V3z8JC7qSDx/vYvI/S3Iz14Bv7CYWXY+N2uQj701LraX5ViMd+Dx0hzSMRIfnpYe+sb/wMJflKzsFEfybXAAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 멀티보드(종이와 깃펜)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJDSURBVDhPnZDPT5JxHMcf1moeO3Zxi61LLQ9wyDEXJl4KzR9sNiDiN6RgP5lGIj/3ACoMZpihoqAMC5EKHW1t0fLCptZjrbRLoyNH/4R3D18Xiz0dnIf3Pvtu39fr/dmH2k1TOG5M/UehKArFYgFSiQREwOPxjhWRSITDwyqJQCA4kv0V/P4QwX6Bxs/NAJicE7/eh7GX96KccWDOdRvhMI3KAQOmXGJFArJFg+Ar+/lb3oP9DT/21t3YzTqx88qJBa8GmUwClcoBGKYMh8MG0aVmwtTYuuBLzs2CHgL+KLCS1z7M+1TIJBKoVisoFfOwWQ2QCPjQdbf/T+DF5zUPvm8Esf3Sia3UKGwGGdvKkPWbmigCG3quQdsl5gp2sh5sZ91g8jQ+Lo7AYZUh/0/r3f5OGHs7SLtaepUr2FoZw7vZ+/iUsmPJrYFBKYPVoAT/3FkopG0wsbD+Zjtc5h6shizkiA2CUtKOt9MWFGLDpJGmaTLNfRLcui6EZ7APueg9JHxaLNIGrmA9OoTii8fIhs1k9RqsudGGqUcKpCeMSNJ6LAdMSE8OYslv4grexB5gLWKpNwetvchMmllQR+C4SwWrvAPDik48H7/DFayGhhB+OACx8ALOnD6FK5fPo7WFj5UJM5aDZhaUIDamxLRdAXV3K1cw71GT46QCRnSJW5D0GxF3qyG82Mw2SzDn1SH6RI5ZlxaxcXWjoPaYYe1xl5q0PHuqIFnw6THjUBEwZBtAZFSOKXaGR+RcwUlSF5w8FP4AEDYoTQv0ZVgAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 애니메이션(움직이는 구슬)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJ5SURBVDhPnZJdTI5hGMev53nuesv7vpuZGo0Tc2BtWJuyfC4rGwptNR9pVEtpMilNH6JkqhWFvmSSYjLMAQ0TYZUoZmKcOTCbObCZ2kR+7ueNrfCeOPg/9+7nvq7f9b/u65YnrcLjc0J3s9B1SuisH9P9JqFH/7PP7Bhvkr4W/ZH/kwdwr3FsM3WyEBosxCwT4qNMloQYTHZPTPhTHsDVSiEoQIhYIKxbbpCxQZGa4MPGWEVEqInb+Xfib3kALcXConlCZJgQvdRkyxpFYrwiL92isdCiPt8iOdZkRqAXwKlCYa2uHLlQWDzfYGu0SWmmSYNOftjsx52L/rTWOdifppg+9R+AMweEDSstNq8yCZljkJMoHEw3qNytOHvIQWGuL8lJik2rFXNnGxMAd/S05HKFEDzLIHm9xYowizJdPStBSFil3cQo8lNNqvcKt0/qkbYqLpVZpOiWXP7CsWwNuPtrCkEBBuHzLBoKfCnarojSLRWni3Yi3Kw1+dDpz8igi2/vXAw/d9JUZLEjTuf++Q7C55ukxVnkJRlUZYlH3c0+jAy4GP3o5vuo27N+eeTUzkw8L3E8wFbgFAP7cu3qtnrO+jL6bCzxN+Brv4vORuvfAFsdxw2qc4TDGcL1GsVwrxNeu/nx3g1vtINuJy/alXeAXfVWnaJ8l8GJXIOnFxwM9boY0ZWHepy87fDhWpWO9QZoLfXh04NJdJ32pTrbpEa76ThhMXhJ8eqyov+8UKIv2Stg5jSDriYHn7XVvjYHtftMjuwUDRNaSoTcbUJGvI61AeNlT+VGjXAkU0iNNWgvV7y84seAbqGt1KJCt1SQIiSvFY7uEX4C9ibSbLPa1DYAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 플레이어 그룹(4색 플레이어 시작 지점)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFgSURBVDhPpZG/SwJxGMZf71JQzzI1FLl+gNhiQ1NB0J+QEUQ1tYQIEi0N0Rg4trW1heDSGv0TTg1N4RJuzk4ST897p3ac3yOo4cO9PO/zPN8v95VeR/AfvAKRvxFZ0JAYntcEkIKHzqqFfZEFfXEYTGAkcQ+dVQv75gvcImTz0J+zAX066049E31WYNuCYopX/iR9iiuZn/AUatuDMraIU7AgzHgFt02G3snQLzg5CgUDpA+SXkGV7JBaKwXJLQq0ZAQWjAU3DXNYKbUclAcuqaJ06WAhy5s0eGKGPwlvgjFLXh7NYaXylGN4A3s8PZ2IQbPeP7Aswem+4OI4EFitGef8WQpuPQmJRT1jnO/9wJe7JusVH51V013AO1+wXIC0vyBNmndJd4LOqulOPZEFtg2p30PuaD7/gFzxq+ismu7UE1kQ5pUhxbQjvxe0hz6mHZkVmNAnyi/56Gzy9DqCbxiAnt7oovj/AAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 플레이어(파란색 플레이어 시작 지점)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE6SURBVDhPpZG7SgNREIYnBisJ3gmCYiGIYKNVOhttbAw22glBg5U2KYKFhRBstLPwAQI2tuJL5BHEJ7C2lPH/9uy6YfcsghYfO/yXYThro6H5f0gWmP2N6gVbXbftZ7c7DzCjFXLVC3rvbtcq9j8DzGiFXHnBctNtvR3mmTE9m/HIpHq+oFZ3a8q4TU9ebOTlDDQ8MmTVSbpL+x23B4mciblxVC5n4JEhq07Stak5t70rt47EC7HbLxcz8MiQpUO3eyijUXN7lHguzl7iZcAjQ1adpBveYMJt59itdZqHVzbjMxmy6uSPmJkwqWt4k55YXQswo+GNZcsLZhfcBl/hzJZ4SmFGwyNTuaCu33lw73aj8Mmb26W+wIyGR6ZyQZFXlSDmid8XDD4CMU/8LIjBL5qfDjDHMqOh+TfUCKKeI7Q1MgAAAABJRU5ErkJggg==",
            // 트리거 아이콘 - 타이머(시계)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACqSURBVDhPrZCxDcIwEEVvqAzgASjSU7BFBsgCFJR00CFGQMoAWYCeQYye0ZHTxbasQPGU8/nfy8kyXyX+QhKIbKMqeJw+nIel9pmiIBfO9bMCQrtO4u1yTIQQvrXea3YlsMOHfR9fzykJ+HL2kpXgPi4ChqwAVECuKtC/A30kQL9JYDewNG9A0G4B9g2KAi9Rkdb0dbgoAJV47DAUBUDY4zNVQQv/E2xH4hvX1s3jf1VdiQAAAABJRU5ErkJggg==",
            // 트리거 아이콘 - 다이얼로그(느낌표)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAC5SURBVDhPYzi9mOE/DJ9cyPB/Uz/D/+ZMhv+Jfgz/Iz0Y/sf7MPwvjmH4P6ua4f++mQi1MAw2gIEBFbsAMZABx7uBGF0NCA9iA4yBGMiA41VAjK4GhHEaAMJAAo7LoWLoGK8Bd4EYyADjUKgYOsZrAMjfQAYYg8IEmxq8BoCcDWSAMTZ5EMZrADGYtgYACTgmKxaAxAAbQAyGG4CMj85n+L99MsP/lR0M/5e1Quhtk4Di81DVQTDDfwDkxHXrbogiKAAAAABJRU5ErkJggg==",
            // 트리거 아이콘 - 주석(노란색 줄글)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABRSURBVDhPzdCxDQAgCETR238Nx3EoDVQIiIiNxYshkF+I3jBecACoWQLyzTCBCjdAc8Y2cMMN0KzJvcS76ODks4B8M0ygwg3QHNG3n3xiHcYETsOVLrNaH+cAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 주석(초록색 줄글)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABXSURBVDhPYzi9mOE/JRhsAAMDeRjFAO6rCJoYjGEAORirAdhsw4ZxGkAKJtoFyPLImDYuIAVT1wCYX9H9jwtjGEAOxmoANtuQMbJa2riAFAw3gHzM8B8A8tx8OIucFcEAAAAASUVORK5CYII=",
            // 트리거 아이콘 - 카메라/시네마틱(카메라)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACeSURBVDhPpdDBCoMwDIDhIOywgxcPOwz29HscryKyMcbYHsJbtLEtSZpq6Q4fhKz+q0J/B/wHBQDqJAF8nwk/ZO0CEcDPScjtOBn4NkJux4mAg78NP2TtAhGYn+s11T9q4cEwpwH1zho9zOY04L94CTvwanfRDdicBh7dLneOIn4WAQ2nS2T97mQDOF6JnjUzgMONHO2c7A1KxUA9wAW1jP4DBKt66wAAAABJRU5ErkJggg==",
            // 트리거 아이콘 - 아이템(상자)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJ3SURBVDhPdZNbTxpRFIWnarmMTAVEo6YCAsMIjBcEBimj3MFouRRlvCCgaZpgtNE0KRjbarFJbZumbyS+9+f0R63OHKKihIeVyeTs/e2z916H+veXQrduLyh8KFMoJTtf5f9pTLcIgKIe5HA4cHV1hfcnx9jb2wNN04/Ou/UIoASm0ymUSiVkMhmkVpdQEIx4F2ewJQxjhdNgUj/YH5DP51HIvUZ8wQSvWY24R4sNrxY32wZ8lww4z45A9HPkdpubm6QgyVV6ZO1WGZBDkNOjIo7g44Yepxk9yuEXWHZosOLUYi3EkuRYLAqe58GyLJkPpQyq9fUzPl00EZo3IyVYEXHrkJjT4SDCYF9kkPMbUCwW4fF44HJMw2k3IxqNkiFTyrRPjus4P2+gILfx6+cN/vz+ASkbxfKsET4bDb97CqFgAEbdIBYtWsw5JiCKYbIpApAkiVQQBAGNRoNUarfbyGazMvwIhwdVpJJJWMdVsE2oMcux2C/vPgDOzk7Bu12w2WaQy+VwdFTHt+trRCIRtFotXF5+Qb1eh9e7KIMSeHtYIy3cA2q1KgLcKOJuDZZc0/B5eezuSBACPgSDQXK7ZrOJTDqNrcI6xkYNEMOvHgDF4huE56awvjgs75yByNHgpjSy1DAxgwgv+7Eme8PEDME8piLF/L6l/gBFIZaWpe0BKMk9AMVI7IwZCxY1/HYamXkdUZLXwSYPrrxTQq1aBSsP8A6QiMc6AGKGLnvax5/D/VKDVReNBD8M56QaxfwGtrclOM1GkqxnaFgslo4PngLuRKsHYDGpYJV7VtZZqVQIdGjg2X0MyVX83E9KwN3TVtT7vCn8B2tFsqJQ9wdrAAAAAElFTkSuQmCC",
            // 트리거 아이콘 - 사운드(스피커)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAC8SURBVDhPnZKxCgJBDETzn9b+gKU/opVwWtldJdqK1fkPgrWdYB2ZXWZJgruuFo9cws3sbFi57kR7WS9FF7NcOUsGIn2cjgfX/2QQxQBJmgZ6yzWK0QNcp2oAsb5GN6OQfTVBEj9XLoEVErcD/mzFnNVwCYroMS9iGjBBxO3gfhE970WnMYMe8LRPuAQQs1oTzLbDJkEhcTuwWBM7j0bNd0ATfMfTadR8B4DXAtEEfH2JkWhS3UEvxeB/RN/5Qbz5gCAHVAAAAABJRU5ErkJggg==",
            // 트리거 아이콘 - 대기(ZZZ)
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACoSURBVDhPYzi9mOE/JZjh6HwgwUAeBhuwfTKmBLEYbMC6bggHSGDF6JqQMU4XAAmCmkEYbMDB2aiCQIIozSAMNmB1J0IASMA1b8aBYWpBGGxAQzqEAyRw2oxNMwiv7ADSGSEIzegYn2YQTvQD0q3ZmBIwjK65HAvGmQ5gmtExSA6m2d4IyAcHBFSCGAy3GYhJNgCmGRmT7AJkDA5ESgwARyPIAPIxw38Ait9yYFpwRVQAAAAASUVORK5CYII=",
        ];

        public ToolSampleIcons()
        {
            InitializeComponent();
            LoadSampleIcons();
        }

        /// <summary>
        /// 샘플 이미지를 로드하고, 컨트롤에 추가합니다.
        /// </summary>
        private void LoadSampleIcons()
        {
            foreach (var base64String in SampleImagesBase64)
            {
                // 이미지를 생성하여 컨트롤에 추가
                var sampleImage = CreateSampleImage(base64String);
                SampleIconContainer.Children.Add(sampleImage);
            }
        }

        /// <summary>
        /// Base64 문자열을 이미지로 변환하고, 설정된 스타일의 Image 컨트롤을 생성합니다.
        /// </summary>
        /// <param name="base64String">Base64 문자열</param>
        /// <returns>Image 컨트롤</returns>
        private static Image CreateSampleImage(string base64String)
        {
            var image = new Image
            {
                Width = 20,
                Height = 20,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Top,
                Margin = new Thickness(0, 0, 0, 10),
                Source = Base64Helper.Convert(base64String),
                ToolTip = "클릭하여 이미지를 클립보드에 복사합니다."
            };

            // 이미지 클릭 시 복사 동작 설정
            image.MouseDown += (_, _) => CopyImageToClipboard(image);

            // 이미지 스케일링 모드 설정
            RenderOptions.SetBitmapScalingMode(image, BitmapScalingMode.NearestNeighbor);

            return image;
        }

        /// <summary>
        /// 이미지를 클립보드에 복사하고, 복사 완료 메시지를 표시합니다.
        /// </summary>
        /// <param name="image">복사할 Image 컨트롤</param>
        private static void CopyImageToClipboard(Image image)
        {
            // 이미지 소스를 클립보드에 복사
            if (image.Source is BitmapSource bitmapSource)
            {
                Clipboard.SetImage(bitmapSource);
                Messenger.Send(new OverlayMessageBox.ShowActionMessage("아이콘을 클립보드에 복사했습니다."));
            }
        }
    }
}
